### ISSUE TITLE
add input to run sleep in seconds after cancel

### ISSUE THREAD

**Issue by copdips** [andymckay/cancel-action#12]
Hello,

As this action triggers an asynchronous cancel to current running workflow, is it possible to add an additional input that users can add an additional sleep time.
Currently, I must run an additional sleep in a bash step after cancel, which works, but embed this into this action would be more elegant

**Comment by andymckay** [comment]
I'd be a little worried about anything going into a sleep and potentially consuming minutes this way. Maybe polling the Actions API and waiting for it to report cancelled might be better? If it doesn't reply as cancelled with 10 minutes, then give up and fail.

Alternatively, we could just add an "exit immediately" after sending the cancel API request I believe?

**Comment by copdips** [comment]
I asked for the sleep time is in case of a conditional cancel-action, say sth like below:

```yaml
steps:
 - run: create a var named test
 - name: cancelling
   if: test is true
   uses: andymckay/cancel-action@0.3
 - run: continue if not cancelled
````

Without the sleep step, the next step `run: continue if not cancelled` will be triggered every time. regardless of whether the `if` condition is true or false, which is unexpected.

yes, an additional sleep with timeout (given as action input) is a good idea I think.

I'm not sure if an immediate exit is suitable or if it's easy to implement as we need to cancel the whole workflow.
