### ISSUE TITLE
Cancelling doesn't prevent future steps from being completed

### ISSUE THREAD

**Issue by adam-berrio** [andymckay/cancel-action#2]
It appears that when you cancel with the GitHub API its some what asynchronous. So if you have steps that follow shortly after using cancel-action (i.e. when using cancel-action with an if statement) the following steps will execute until GitHub has caught up. 

Example:
```
jobs:
    publish:
        name: Tag & Publish Main
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.tag_outputs.outputs.version }}
        steps:
            # Check if we should skip
            - name: GitHub | Check PR Labels
              id: skipVersion
              uses: shioyang/check-pr-labels-on-push-action@v1.0.3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                labels: '["skip-version"]'
            - name: GitHub | Label Result
              run: echo "'skip-version' tag found. Skipping Tag & Publish."
              if: steps.skipVersion.outputs.result == 'true'
            - name: GitHub | Cancel Tag & Publish
              uses: andymckay/cancel-action@0.2
              if: steps.skipVersion.outputs.result == 'true'
            # Checkout the code
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            # Tag build to get version
            - name: GitHub | Tag build
              id: version
              uses: anothrNick/github-tag-action@1.34.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  RELEASE_BRANCHES: main
                  VERBOSE: true
```

In the example above, when I add the `skip-version` tag in my pull request, I get a `Cancelled Successfully` response from cancel-action, but the steps continue, and the code is tagged.

Is there a way to wait until the cancel is acknowledged and completed by GitHub?
